# Generated by Django 2.2.4 on 2019-08-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=5)),
                ('codigo', models.CharField(blank=True, max_length=5)),
                ('descrip', models.CharField(max_length=79, null=True)),
                ('valor1', models.IntegerField(blank=True)),
                ('valor2', models.IntegerField(blank=True)),
                ('valor3', models.IntegerField(blank=True)),
                ('sw_1', models.IntegerField(blank=True)),
                ('sw_2', models.IntegerField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(blank=True)),
                ('corr', models.IntegerField(blank=True)),
                ('fecha2', models.DateTimeField(blank=True)),
            ],
        ),
    ]
